site_url : https://asalvadorc.github.io/BBDD_Tema4
site_name: BD - Bases de Dades
theme: 
  name: readthedocs
  logo: assets/logocaminas.png

extra_css:
  - css/extra.css
  - img/favicon.ico 
nav:
  - Normalització:
    - Objectius: BD-T04_Normalizacion/objectius.md
    - 1. Introducció: BD-T04_Normalizacion/1_introducci.md
    - 2. Primer Forma Normal (1FN): BD-T04_Normalizacion/2_primer_forma_normal_1fn.md
    - 3.  Dependència Funcional: BD-T04_Normalizacion/3_dependncia_funcional.md
    - 4. Segona Forma Normal (2FN): BD-T04_Normalizacion/4_segona_forma_normal_2fn.md
    - 5. Dependència Funcional Transitiva: BD-T04_Normalizacion/5_dependncia_funcional_transitiva.md
    - 6. Tercera Forma Normal (3FN): BD-T04_Normalizacion/6_tercera_forma_normal_3fn.md
    - 7. Forma Normal Boyce-Codd (FNBC): BD-T04_Normalizacion/7_forma_normal_boycecodd_fnbc.md
    - Resum: BD-T04_Normalizacion/resum.md
    - Exercicis: BD-T04_Normalizacion/exercicis.md
    